name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # Build the application
      - name: Build Application
        run: pnpm tauri build

      # Upload release artifacts
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tauri-App-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Create a GitHub Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/windows/*.exe
            src-tauri/target/release/bundle/linux/*.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release was automatically generated by the GitHub Actions CI/CD workflow.
